<a href="https://colab.research.google.com/github/Sayfiddinova00/github-uchun/blob/main/github1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
from pandas import Series

In [ ]:
obj=Series([4,7,6,-5,-4.5])

In [ ]:
print(obj)

0    4.0
1    7.0
2    6.0
3   -5.0
4   -4.5
dtype: float64

In [ ]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
obj.values

array([ 4. ,  7. ,  6. , -5. , -4.5])

In [ ]:
obj[0]

np.float64(4.0)

In [ ]:
obj2=Series([1,2,3], index=['a', 'b', 'c'])

In [ ]:
obj2

a    1
b    2
c    3
dtype: int64

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving pandas_homework_dirty_data_2150_rows.csv to pandas_homework_dirty_data_2150_rows.csv

Saving talabalar.csv to talabalar.csv

In [ ]:
df = pd.read_csv('pandas_homework_dirty_data_2150_rows.csv')
df.head()

   order_id    shop  product     city amount   shop_date
0         1  Shop B   Laptop  Bukhara   3950  16.01.2025
1         2  Shop E   Laptop      NaN   1393         NaN
2         3     NaN  Monitor      NaN  1,200  17.09.2025
3         4     NaN      NaN  Bukhara   2456  21.01.2025
4         5     NaN   Laptop      NaN   4715  14.01.2025

In [ ]:
df.isnull().sum()

order_id       0
shop         610
product      601
city         618
amount       335
shop_date    224
dtype: int64

In [ ]:
df.shape

(2150, 6)

In [ ]:
df.isnull().any()

In [ ]:
f.isnull().any()f.isnull().any()

In [ ]:
df.head

In [ ]:
df["name"] = df["name"].str.strip()

In [ ]:
df.["gender"]